version: '3.9'

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map localhost:3000 to the container's nginx port 80
    container_name: vite-react-app
